# fly.toml app configuration file generated for realchar-web on 2023-08-25T20:52:15+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "realchar-web"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
