name: Build Push and Deploy Backend Docker Image

on:
  release:
    types: [published]  # This triggers the workflow when a release is published
  push:
    branches:
      - "kevin/main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: taokevin1024/realchar-backend:latest

  deploy:
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          script: |  
            cd /home/kevin/project/realchar
            docker pull taokevin1024/realchar-backend:latest
            docker run -d --env-file .env --name realchar-backend -p 8000:8000 taokevin1024/realchar-backend:latest