name: CI/CD Pipeline

env:
  CONTAINER_NAME: ctr-realchar
  REPO_PROJECT: realchar
  IMAGE_VERSION: latest
  HOST_PORT: 8080
  CONTAINER_PORT: 8000

on:
  push:
    branches:
      - "main"
      - "kevin/main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_PROJECT }}:${{ env.IMAGE_VERSION }}

  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        # - name: Copy .env file to server
        #   run: scp -i ${{ secrets.SERVER_SSH_KEY }} -o StrictHostKeyChecking=no .env ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/kevin/projects/realchar/.env

        - name: Deploy to Server
          uses: appleboy/ssh-action@v0.1.1
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              cd /home/kevin/projects/realchar/
              docker-compose down
              docker-compose pull
              docker-compose up -d
