name: CI/CD Pipeline

env:
  CONTAINER_NAME: ctr-realchar
  REPO_PROJECT: realchar
  IMAGE_VERSION: latest
  HOST_PORT: 8080
  CONTAINER_PORT: 8000

on:
  push:
    branches:
      - "main"
      - "kevin/main"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_PROJECT }}:${{ env.IMAGE_VERSION }}

  deploy:
    runs-on: ubuntu-latest   
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        # Don't forget to add environment vars as secrets in repository settings on GitHub
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |  
            cd /home/kevin/projects/realchar
            git pull origin main 
            make down-v
            make build
            echo "Deleting old image(s)..."
            docker image prune -a -f